### ISSUE TITLE
Does it support other IdP products (Google, PingIdentity etc.)?

### ISSUE THREAD

**Issue by ahmetsonmez** [FabianZoon/SCIM2#1]
Hi,

Does it support other IdP products (Google, PingIdentity etc.)? 

So can we use this code base to support all SCIM IdPs?

Regards.
Thanks.

**Comment by FabianZoon** [comment]
Hi Ahmet,
SCIM is a standard, so on that part it should work.
But the library is only implemented the parts needed for Okta (at this moment). E.g. the Filtering option of RFC7644 is quite extensive and is not available.
But the basic should be the same.
Kind Regards,
Fabian

**Comment by ahmetsonmez** [comment]
Thanks a lot for the quick reply.
